### ISSUE TITLE
Adding API requests for Anonymizing/Unanonymizing Posts

### ISSUE THREAD

**Issue by parthr01** [CMU-313/spring24-nodebb-cute-capybaras#29]
Effort: Medium
Dependencies: anonymize and unanonymize attributes for posts (?)
Assignees: Backend (Parth Rustagi)
Milestone: Sprint 2
Acceptance Criteria: Users should be able anonymize and unanonymize posts via API requests

**Comment by TishyaaChaudhry** [comment]
Duplicate of #23
